/**
 * Renders the pack's TeX formulas to static HTML at BUILD time.
 *
 * This is decision C3. The runtime ships no KaTeX JavaScript: the browser receives
 * ready-made markup plus the stylesheet and the font subset.
 *
 * Measured in M0, so the trade-off is on the record rather than assumed:
 *   katex.min.js   275,414 B raw   75,488 B gzip
 *   katex.min.css   23,335 B raw    3,433 B gzip
 *   4 typical woff2 faces          73,504 B (not gzip-compressible)
 *
 * The 250 KB budget closed either way — ~117 KB build-time vs ~192 KB runtime — so
 * weight was NOT the reason. The reason is CPU: a weak machine never has to parse and
 * execute 275 KB of JavaScript, which is criterion 5 of the bake-off.
 *
 * Usage: node pipeline/render_math.mjs content/packs/<pack>
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve } from "node:path";
import { createRequire } from "node:module";

// katex lives in app/web/node_modules, not next to this script
const require = createRequire(resolve("app/web/package.json"));
const katex = require("katex");

const packDir = resolve(process.argv[2] ?? "content/packs/budget-line");
const outFile = resolve("app/web/src/generated/formulas.ts");

// Minimal YAML reader for the `notes:` block. A full parser is not worth a dependency
// here: the block is machine-written and its shape is fixed.
const raw = readFileSync(join(packDir, "pack.yaml"), "utf8");
const notesBlock = raw.split(/^notes:\s*$/m)[1] ?? "";

const notes = {};
let current = null;
for (const line of notesBlock.split("\n")) {
  if (/^\s*#/.test(line) || !line.trim()) continue;
  const key = line.match(/^ {2}([a-z_]+):\s*$/);
  if (key) { current = key[1]; notes[current] = {}; continue; }
  if (!current) continue;
  const field = line.match(/^ {4}(en|es|formula|formula_dim):\s*(.*)$/);
  if (!field) continue;
  let value = field[2].trim();
  if ((value.startsWith("'") && value.endsWith("'")) ||
      (value.startsWith('"') && value.endsWith('"'))) {
    value = value.slice(1, -1);
  }
  notes[current][field[1]] = value;
}

/** Tags each term so the runtime can highlight one symbol in the equation, on its good
 *  card and on the graph AT THE SAME TIME — the coherence the design is built around
 *  (A4). Zero runtime cost: this is markup we already generate.
 *
 *  Done at the TeX level with KaTeX's own `\htmlData`, NOT with regex over the rendered
 *  HTML. The regex version was written first and was silently wrong: sequential
 *  replacements operate on already-modified markup, so the `p_2` pass re-wrapped the
 *  span the `p_1` pass had just created, and terms came out mislabelled. A mislabelled
 *  term makes every cross-highlight lie, which is worse than no highlighting at all.
 */
const TERMS = ["p_1", "p_2", "x_1", "x_2", "m"];

function tagTex(tex) {
  let out = tex;
  for (const term of TERMS) {
    const id = term.replace("_", "");
    // \b-style guard: a bare `m` must not match the m inside \frac, \mathrm, kg…
    const pattern = term === "m"
      ? /(^|[^\\a-zA-Z])m(?![a-zA-Z])/g
      : new RegExp(`${term[0]}_${term[2]}`, "g");
    out = term === "m"
      ? out.replace(pattern, (_, pre) => `${pre}\\htmlData{term=m}{m}`)
      : out.replace(pattern, `\\htmlData{term=${id}}{${term}}`);
  }
  return out;
}

const render = (tex) => katex.renderToString(tagTex(tex), {
  displayMode: true,
  throwOnError: true,        // a broken formula must fail the build, not ship
  output: "html",
  strict: false,             // \htmlData is an extension
  trust: (ctx) => ctx.command === "\\htmlData",
});

const entries = Object.entries(notes).map(([id, n]) => [id, {
  en: n.en ?? "",
  es: n.es ?? "",
  formulaHtml: n.formula ? render(n.formula) : null,
  // The dimensional form (codex, T-010): units inside the equation, shown before the
  // compact one. Null where the note has no dimensional variant.
  formulaDimHtml: n.formula_dim ? render(n.formula_dim) : null,
}]);

const ts = `// GENERATED by pipeline/render_math.mjs — do not edit.
// Source: ${packDir.replace(resolve("."), ".")}/pack.yaml
// KaTeX is rendered here, at build time, so the runtime ships none of it (C3).

export interface Note {
  en: string;
  es: string;
  formulaHtml: string | null;
  /** Dimensional form, units inside the equation. Shown before the compact form. */
  formulaDimHtml: string | null;
}

export const NOTES: Record<string, Note> = ${JSON.stringify(
  Object.fromEntries(entries), null, 2)};
`;

mkdirSync(resolve("app/web/src/generated"), { recursive: true });
writeFileSync(outFile, ts, "utf8");

const withFormula = entries.filter(([, n]) => n.formulaHtml).length;
const withDim = entries.filter(([, n]) => n.formulaDimHtml).length;
const tagged = entries.reduce((a, [, n]) =>
  a + ((n.formulaHtml ?? "").match(/data-term=/g) ?? []).length, 0);
const bytes = Buffer.byteLength(ts, "utf8");
console.log(`${outFile.replace(resolve("."), ".")}`);
console.log(`  ${entries.length} notes, ${withFormula} formulas (${withDim} dimensional), ` +
            `${tagged} tagged terms, ${(bytes / 1024).toFixed(1)} KB of markup`);
