import {abrir, SNAP} from './nav-lib.mjs';
const errores=[];
const {browser,page} = await abrir('http://localhost:57330/?lang=es', {errores});
await page.evaluate(()=>window.__tutoria.media.seek(110));
await page.waitForTimeout(500);
await page.click('#ask');
await page.waitForTimeout(1200);
let s = await page.evaluate(SNAP);
console.log('tras #ask:', JSON.stringify({t:s.t, paused:s.paused, play:s.play, dock:s.dockEstado, dockActual:s.dockActual, body:(s.dockBody||'').slice(0,120)}));
await page.fill('.composer-input', '¿por qué la pendiente es negativa?');
await page.click('.composer-enviar');
await page.waitForTimeout(9000);
s = await page.evaluate(SNAP);
console.log('tras enviar:', JSON.stringify({t:s.t, paused:s.paused, dock:s.dockEstado, dockActual:s.dockActual, body:(s.dockBody||'').slice(0,300)}));
await page.screenshot({path:'/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/tutor.png'});
// saltar atras con la respuesta del tutor abierta
await page.evaluate(()=>window.__tutoria.media.seek(20));
await page.waitForTimeout(1500);
s = await page.evaluate(SNAP);
console.log('tras seek(20):', JSON.stringify({t:s.t, paused:s.paused, play:s.play, dock:s.dockEstado, dockActual:s.dockActual, mostrar:Object.entries(s.estado.mostrar).filter(([,v])=>v).map(([k])=>k).join('+')||'nada', body:(s.dockBody||'').slice(0,200)}));
await page.screenshot({path:'/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/tutor-seek20.png'});
if(errores.length) console.log('ERRORES', errores);
await browser.close();
