import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const OUT='/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/shots';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:1280,height:860}});
const page = await ctx.newPage();
page.on('pageerror', e => console.log('  JS ERROR:', String(e).slice(0,300)));
page.on('request', r=>{ if(r.url().includes('/chat')) console.log('   -> POST chat'); });
await page.goto('http://localhost:57330/?lang=es&t=0', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0');
console.log('=== A) chips con presupuesto disponible ===');
await page.click('#ask'); await page.waitForTimeout(500);
await page.click('.dock >> text=No entiendo');
await page.waitForTimeout(6000);
console.log('dock:', (await page.evaluate(()=>document.querySelector('.dock').innerText)).split('\n').filter(x=>x.trim()).join(' | ').slice(0,500));
console.log('contador:', await page.evaluate(()=>document.querySelector('.composer-restantes')?.innerText));
await page.screenshot({path:OUT+'/p7-chip.png'});
console.log('=== A2) chip "Listo, sigamos" ===');
const antes = await page.evaluate(()=>({dock:window.__tutoria.dock.actual,paused:window.__tutoria.media.paused()}));
await page.click('.dock >> text=Listo, sigamos'); await page.waitForTimeout(2500);
console.log('antes',JSON.stringify(antes),'despues',JSON.stringify(await page.evaluate(()=>({dock:window.__tutoria.dock.actual,paused:window.__tutoria.media.paused(),cur:+window.__tutoria.media.currentTime().toFixed(1)}))));
console.log('=== B) cambio de idioma a mitad ===');
if(await page.evaluate(()=>window.__tutoria.media.paused())) await page.click('#play');
await page.evaluate(()=>window.__tutoria.media.seek(100)); await page.waitForTimeout(2000);
console.log('antes de cambiar idioma:', JSON.stringify(await page.evaluate(()=>({cur:+window.__tutoria.media.currentTime().toFixed(1), url:location.href}))));
const href = await page.getAttribute('a.idioma','href'); console.log('href del enlace idioma:', href);
await page.click('a.idioma');
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0');
await page.waitForTimeout(1200);
console.log('tras cambiar idioma:', JSON.stringify(await page.evaluate(()=>({cur:+window.__tutoria.media.currentTime().toFixed(1), url:location.href, paused:window.__tutoria.media.paused(), play:document.querySelector('#play').innerText}))));
await page.screenshot({path:OUT+'/p7-idioma.png'});
console.log('body:', (await page.evaluate(()=>document.body.innerText)).replace(/\n/g,' | ').slice(0,300));
await browser.close();
