import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const OUT='/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/shots';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:1280,height:860}});
const page = await ctx.newPage();
page.on('pageerror', e => console.log('  JS ERROR p1:', String(e).slice(0,300)));
await page.goto('http://localhost:57330/?lang=es&t=0', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0');
console.log('=== A) toggle del dock con #ask ===');
await page.click('#play'); await page.waitForTimeout(1500);
await page.click('#ask'); await page.waitForTimeout(600);
console.log('tras 1er ask:', await page.evaluate(()=>window.__tutoria.dock.actual), 'paused', await page.evaluate(()=>window.__tutoria.media.paused()));
await page.click('#ask'); await page.waitForTimeout(800);
console.log('tras 2o ask:', await page.evaluate(()=>window.__tutoria.dock.actual), 'paused', await page.evaluate(()=>window.__tutoria.media.paused()), 'play btn', await page.innerText('#play'));
await page.click('#ask'); await page.waitForTimeout(600);
console.log('tras 3er ask:', await page.evaluate(()=>window.__tutoria.dock.actual), 'paused', await page.evaluate(()=>window.__tutoria.media.paused()));
console.log('=== A2) tecla Escape con dock abierto ===');
await page.keyboard.press('Escape'); await page.waitForTimeout(500);
console.log('tras Escape:', await page.evaluate(()=>window.__tutoria.dock.actual));
console.log('=== B) clic en el lienzo vacio y en las fichas ===');
await page.click('.lienzo', {position:{x:300,y:200}}).catch(e=>console.log('  no hay .lienzo clicable',String(e).split('\n')[0]));
await page.waitForTimeout(400);
console.log('estado tras clic lienzo:', JSON.stringify(await page.evaluate(()=>window.__tutoria.estado().destacar)));
const cards = await page.$$('.bands .band, .bands > *');
console.log('elementos en .bands:', cards.length);
await page.click('.bands >> text=Café').catch(e=>console.log('  ficha no clicable'));
await page.waitForTimeout(400);
console.log('=== C) toggle de subtitulos ===');
await page.click('.caption-toggle'); await page.waitForTimeout(500);
console.log('texto boton:', await page.innerText('.caption-toggle'), '| banda visible:', await page.evaluate(()=>{const c=document.querySelector('.captions-band'); return c? getComputedStyle(c).display+'/'+c.innerText.slice(0,40):'no existe';}));
await page.screenshot({path:OUT+'/p9-sinsubs.png'});
console.log('=== D) dos pestañas a la vez ===');
const page2 = await ctx.newPage();
page2.on('pageerror', e => console.log('  JS ERROR p2:', String(e).slice(0,300)));
await page2.goto('http://localhost:57330/?lang=es&t=0', {waitUntil:'domcontentloaded'});
await page2.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0');
await page2.click('#play'); await page2.waitForTimeout(2500);
const s2 = await page2.evaluate(()=>({cur:+window.__tutoria.media.currentTime().toFixed(1),paused:window.__tutoria.media.paused()}));
await page.bringToFront(); await page.waitForTimeout(500);
const s1 = await page.evaluate(()=>({cur:+window.__tutoria.media.currentTime().toFixed(1),paused:window.__tutoria.media.paused()}));
console.log('pestaña2', JSON.stringify(s2), 'pestaña1', JSON.stringify(s1));
await page.waitForTimeout(2500);
console.log('ambas reproduciendo a la vez?', JSON.stringify(await page.evaluate(()=>({p1:!window.__tutoria.media.paused(),cur:+window.__tutoria.media.currentTime().toFixed(1)}))), JSON.stringify(await page2.evaluate(()=>({p2:!window.__tutoria.media.paused(),cur:+window.__tutoria.media.currentTime().toFixed(1)}))));
await browser.close();
