import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext(); const page = await ctx.newPage();
const rutas = new Set();
page.on('request', r => { const u = new URL(r.url()); if (/^\/(api|media)/.test(u.pathname)) rutas.add(r.method()+' '+u.pathname.replace(/[0-9a-f]{16,}/,'<id>')); });
await page.goto('http://localhost:8080/?lang=es', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0', null, {timeout:30000});
await page.evaluate("window.__tutoria.media.seek(85); window.__tutoria.media.play()");
await page.waitForTimeout(5000);
console.log('  durante la NARRACIÓN:');
for (const r of [...rutas].sort()) console.log('   ', r);
await browser.close();
