import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const page = await (await browser.newContext({viewport:{width:1280,height:860}})).newPage();
await page.goto('http://localhost:57330/?lang=es&t=0', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0', null, {timeout:30000});
const antes = await page.evaluate(()=>{const a=document.querySelector('.idioma').getBoundingClientRect();
  return {idiomaX: Math.round(a.x), controles: getComputedStyle(document.querySelector('.controles')).display};});
console.log('con el span presente:', JSON.stringify(antes));
await page.evaluate(()=>document.getElementById('desfase').remove());
const despues = await page.evaluate(()=>Math.round(document.querySelector('.idioma').getBoundingClientRect().x));
console.log('tras borrar el span, x del enlace English:', despues);
await browser.close();
