import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const SC='/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:1280,height:860}});
const page = await ctx.newPage();
page.on('pageerror', e => console.log('  JS ERROR:', String(e).slice(0,300)));
await page.goto('http://localhost:57330/?lang=es&t=180',{waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration()>0',null,{timeout:30000});
await page.waitForTimeout(1500);
console.log('ownsStage:', await page.evaluate('window.__tutoria.media.ownsStage'));
console.log('al cargar ?t=180:', await page.evaluate(()=>JSON.stringify({ct:window.__tutoria.media.currentTime(), reloj:document.querySelector('#reloj').textContent, play:document.querySelector('#play').textContent.trim(), grafico:window.__tutoria.estado().mostrar, subtitulo:(document.querySelector('.captions-band')||{}).innerText})));
await page.screenshot({path:SC+'K1-t180.png'});
await page.click('#play'); await page.waitForTimeout(3000);
console.log('tras pulsar Empezar:', await page.evaluate(()=>JSON.stringify({ct:+window.__tutoria.media.currentTime().toFixed(2), reloj:document.querySelector('#reloj').textContent, subtitulo:(document.querySelector('.captions-band')||{}).innerText, grafico:window.__tutoria.estado().mostrar})));
await page.screenshot({path:SC+'K2-t180-tras-play.png'});
await browser.close();
