import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const SC='/private/tmp/claude-502/-Users-klopezva-GithubRepos-tutorIA/1050f3d7-49f3-4d77-9e6b-99bd05c2d5ac/scratchpad/';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:1280,height:860}});
const page = await ctx.newPage();
page.on('pageerror', e => console.log('  JS ERROR:', String(e).slice(0,300)));
await page.goto('http://localhost:57330/?lang=es&t=95', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0', null, {timeout:30000});
await page.waitForTimeout(500);
console.log('al cargar t=95:', await page.evaluate(()=>JSON.stringify({ct:window.__tutoria.media.currentTime(), p:window.__tutoria.media.paused(), play:document.querySelector('#play')?.textContent.trim(), q: !!document.querySelector('.q'), qtxt:(document.querySelector('.q-enunciado')||{}).textContent})));
await page.click('#play');
for (let i=0;i<5;i++){ await page.waitForTimeout(1500);
  console.log(i, await page.evaluate(()=>JSON.stringify({ct:+window.__tutoria.media.currentTime().toFixed(2), p:window.__tutoria.media.paused(), q:!!document.querySelector('.q')})));
}
await page.screenshot({path:SC+'E-t95.png'});
await browser.close();
