import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const d = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, d, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const ctx = await browser.newContext({viewport:{width:1280,height:860}});
const page = await ctx.newPage();
const reqs=[]; page.on('request', r=>reqs.push(r.method()+' '+r.url().replace('http://localhost:57330','')));
page.on('pageerror', e => console.log('  JS ERROR:', String(e).slice(0,300)));
await page.goto('http://localhost:57330/?lang=en', {waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration() > 0', null, {timeout:30000});
const cues = await page.evaluate('window.__tutoriaSesion.media.cues');
console.log('cues NO-graph:', JSON.stringify(cues.filter(c=>c.type!=='graph').map(c=>({id:c.id,t:c.t,type:c.type}))));
const cp = cues.find(c=>c.id && c.id.startsWith('cp'));
console.log('primer cp:', JSON.stringify(cp));
await page.evaluate(`window.__tutoria.media.seek(${cp.t-3}); window.__tutoria.media.play()`);
await page.waitForSelector('.q', {timeout:30000});
console.log('EN reloj=', await page.evaluate('document.getElementById("reloj").textContent'), 'id cue=', cp.id);
console.log('enunciado:', (await page.textContent('.q-enunciado'))?.trim().slice(0,140));
const n0=reqs.length;
await page.click(`.dock-acciones button:text-is("I don't get it")`);
await page.waitForTimeout(10000);
console.log('EN tras chip -> reqs:', JSON.stringify(reqs.slice(n0)));
console.log('EN historial:', JSON.stringify(await page.$$eval('.dock-body .msg', p=>p.map(x=>x.className+'::'+x.textContent.trim().slice(0,90)))));
await browser.close();
