#!/usr/bin/env python3
"""Genera un reproductor autocontenido a partir de la salida de audioexplain.

Por que no usamos el player que trae AudioExplainer: el suyo hace fetch() del audio
y lo pasa a blob, lo cual falla bajo CSP restrictivo (connect-src) aunque el audio
venga como data: URI. Este asigna el src directamente al <audio>, sin fetch ni red.

Diferencias de interfaz pedidas por Kristian:
  - velocidad con - y + en pasos de 5%, en vez de presets fijos
  - saltos de -5s y +5s
  - el texto se lee como una pagina web (titulos y parrafos), no como una lista de
    timestamps; el seguimiento es por oracion dentro del parrafo

Uso:  make-player.py <base-sin-extension> <salida.html>
      espera <base>.mp3, <base>.audio.json y <base>.md
"""
import base64
import html
import json
import pathlib
import re
import sys

base = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])

mp3 = base.with_suffix(".mp3")
side = pathlib.Path(str(base) + ".audio.json")
transcript = base.with_suffix(".md")

meta = json.loads(side.read_text(encoding="utf-8"))
segments = meta.get("sync", {}).get("segments", [])
title = meta.get("title") or base.name
duration = float(meta.get("duration_s") or 0)


def norm(s: str) -> str:
    """Solo alfanumericos en minuscula: tolera puntuacion y espaciado distintos."""
    return re.sub(r"[^0-9a-záéíóúüñ]", "", s.lower())


# --- parsear el transcript en bloques (titulo | parrafo) -------------------
blocks = []
if transcript.exists():
    raw = transcript.read_text(encoding="utf-8")
    lines = raw.split("\n")
    # audioexplain antepone un titulo y una linea "_Generated by ..._"
    start = 0
    for i, ln in enumerate(lines[:6]):
        if ln.startswith("_Generated by"):
            start = i + 1
            break
    buf = []
    for ln in lines[start:]:
        st = ln.strip()
        if st.startswith("#"):
            if buf:
                blocks.append(("p", " ".join(buf))); buf = []
            lvl = len(st) - len(st.lstrip("#"))
            blocks.append((f"h{min(lvl + 1, 4)}", st.lstrip("#").strip()))
        elif not st:
            if buf:
                blocks.append(("p", " ".join(buf))); buf = []
        else:
            buf.append(st)
    if buf:
        blocks.append(("p", " ".join(buf)))

if not blocks:
    blocks = [("p", " ".join(s.get("text", "") for s in segments))]

# --- alinear oraciones con bloques ----------------------------------------
rendered = []
si = 0
for kind, text in blocks:
    target = norm(text)
    if not target:
        continue
    acc = ""
    spans = []
    while si < len(segments) and len(acc) < len(target):
        seg = segments[si]
        st = norm(seg.get("text", ""))
        if not st:
            si += 1
            continue
        # si la siguiente oracion ya no pertenece a este bloque, cortar
        if acc and not target.startswith(acc + st[: max(8, len(st) // 3)]):
            break
        acc += st
        spans.append(seg)
        si += 1
    if not spans:
        # sin alineacion: renderizar el bloque como texto plano, sin seguimiento
        rendered.append((kind, [(None, text)]))
        continue
    rendered.append((kind, [(s, s.get("text", "")) for s in spans]))

# oraciones sobrantes: van a un parrafo final para no perder audio
if si < len(segments):
    rendered.append(("p", [(s, s.get("text", "")) for s in segments[si:]]))

body = []
for kind, parts in rendered:
    inner = []
    for seg, txt in parts:
        t = html.escape(txt)
        if seg is None:
            inner.append(t)
        else:
            inner.append(
                '<span class="s" data-start="{:.3f}" data-end="{:.3f}" tabindex="0">{}</span>'.format(
                    float(seg.get("start_s", 0)), float(seg.get("end_s", 0)), t
                )
            )
    body.append(f"<{kind}>" + " ".join(inner) + f"</{kind}>")

data_uri = "data:audio/mpeg;base64," + base64.b64encode(mp3.read_bytes()).decode("ascii")
mins, secs = divmod(int(duration), 60)


def cuando(iso: str | None) -> str:
    """Cuando se genero este audio, en hora local y en palabras.

    El sidecar lo guarda en UTC con microsegundos — util para ordenar, ilegible para
    saber si un audio es el de hace un rato o el de anoche. Con varios audios en cola,
    esa es la unica pregunta que uno se hace al abrirlos.
    """
    from datetime import datetime, timezone
    if not iso:
        return ""
    try:
        dt = datetime.fromisoformat(iso).astimezone()
    except ValueError:
        return ""
    ahora = datetime.now(timezone.utc).astimezone()
    hora = dt.strftime("%H:%M")
    dias = (ahora.date() - dt.date()).days
    if dias == 0:
        return f"hoy {hora}"
    if dias == 1:
        return f"ayer {hora}"
    MESES = ["ene", "feb", "mar", "abr", "may", "jun",
             "jul", "ago", "sep", "oct", "nov", "dic"]
    fecha = f"{dt.day} {MESES[dt.month - 1]}"
    return f"{fecha} {hora}" if dt.year == ahora.year else f"{fecha} {dt.year} {hora}"


generado = cuando(meta.get("created_at"))

out.write_text(f"""<!doctype html>
<html lang="es"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>
  :root {{
    --bg:#fbfbf9; --fg:#22221f; --muted:#75756e; --line:#e4e4de;
    --accent:#0b5cff; --hl:#fff6cc; --card:#fff;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg:#16161a; --fg:#e9e9e6; --muted:#98988f; --line:#2c2c32;
             --accent:#82a8ff; --hl:#3b3520; --card:#1d1d21; }}
  }}
  * {{ box-sizing:border-box; }}
  body {{ margin:0; padding:1.25rem 1.25rem 4rem; background:var(--bg); color:var(--fg);
    font:17px/1.72 Georgia,"Iowan Old Style","Times New Roman",serif; }}
  .wrap {{ max-width:680px; margin:0 auto; }}
  .eyebrow {{ font-family:ui-sans-serif,system-ui,sans-serif; font-size:.75rem;
    letter-spacing:.06em; text-transform:uppercase; color:var(--muted); }}
  h1 {{ font-size:1.6rem; line-height:1.25; margin:.2rem 0 1.1rem; }}
  h2 {{ font-size:1.2rem; margin:2rem 0 .6rem; line-height:1.35; }}
  h3 {{ font-size:1.05rem; margin:1.5rem 0 .5rem; }}
  p {{ margin:0 0 1.05rem; }}
  .bar {{ position:sticky; top:0; z-index:5; background:var(--card);
    border:1px solid var(--line); border-radius:12px; padding:.8rem;
    margin-bottom:1.6rem; font-family:ui-sans-serif,system-ui,sans-serif; }}
  audio {{ width:100%; display:block; }}
  .row {{ display:flex; gap:.4rem; align-items:center; flex-wrap:wrap; margin-top:.65rem; }}
  button {{ font:inherit; font-size:.82rem; padding:.3rem .6rem; border-radius:8px;
    border:1px solid var(--line); background:transparent; color:var(--fg);
    cursor:pointer; font-variant-numeric:tabular-nums; }}
  button:hover {{ border-color:var(--accent); color:var(--accent); }}
  button:active {{ transform:translateY(1px); }}
  .grp {{ display:flex; gap:.25rem; align-items:center;
    border:1px solid var(--line); border-radius:9px; padding:.15rem; }}
  .grp button {{ border:none; padding:.25rem .5rem; }}
  .val {{ font-size:.8rem; color:var(--muted); min-width:3.4em; text-align:center;
    font-variant-numeric:tabular-nums; }}
  .lbl {{ font-size:.72rem; color:var(--muted); margin-right:.15rem; }}
  @media print {{ .bar {{ display:none; }} }}
  .s {{ border-radius:3px; padding:.03em 0; transition:background .18s ease; cursor:pointer; }}
  .s:hover {{ background:color-mix(in srgb, var(--accent) 12%, transparent); }}
  .s:focus-visible {{ outline:2px solid var(--accent); outline-offset:1px; }}
  .s.on {{ background:var(--hl); }}
  h1 .s.on, h2 .s.on, h3 .s.on {{ background:var(--hl); }}
  .note {{ font-family:ui-sans-serif,system-ui,sans-serif; font-size:.76rem;
    color:var(--muted); margin-top:2.5rem; border-top:1px solid var(--line);
    padding-top:.8rem; }}
</style></head><body><div class="wrap">

<div class="eyebrow">{mins}:{secs:02d} &middot; audio explainer{(" &middot; " + html.escape(generado)) if generado else ""}</div>
<h1>{html.escape(title)}</h1>

<div class="bar">
  <audio id="a" controls preload="metadata" src="{data_uri}"></audio>
  <div class="row">
    <button id="b5">&minus;5s</button>
    <button id="f5">+5s</button>
    <span class="grp">
      <span class="lbl">vel</span>
      <button id="sd" aria-label="Bajar velocidad 5%">&minus;</button>
      <span class="val" id="rate">1.00&times;</span>
      <button id="su" aria-label="Subir velocidad 5%">+</button>
    </span>
    <button id="follow" aria-pressed="true" style="margin-left:auto">Seguir</button>
  </div>
</div>

{chr(10).join(body)}

<p class="note">Reproductor autocontenido: el audio va embebido y el <code>src</code> se
asigna directo, sin <code>fetch</code>, por eso funciona bajo CSP restrictivo. Haz clic en
cualquier oración para saltar ahí. Sin JavaScript los controles nativos siguen
funcionando; sólo se pierde el resaltado.</p>

<script>
(function () {{
  var a = document.getElementById("a");
  var segs = [].slice.call(document.querySelectorAll(".s"));
  var follow = document.getElementById("follow");
  var rateEl = document.getElementById("rate");
  var cur = -1, rate = 1;

  function setRate(r) {{
    rate = Math.min(3, Math.max(0.5, Math.round(r * 100) / 100));
    a.playbackRate = rate;
    rateEl.textContent = rate.toFixed(2) + "\\u00d7";
  }}
  document.getElementById("su").onclick = function () {{ setRate(rate + 0.05); }};
  document.getElementById("sd").onclick = function () {{ setRate(rate - 0.05); }};
  document.getElementById("b5").onclick = function () {{ a.currentTime = Math.max(0, a.currentTime - 5); }};
  document.getElementById("f5").onclick = function () {{ a.currentTime = a.currentTime + 5; }};

  segs.forEach(function (el) {{
    function go() {{ a.currentTime = parseFloat(el.dataset.start) + 0.01; a.play(); }}
    el.addEventListener("click", go);
    el.addEventListener("keydown", function (e) {{
      if (e.key === "Enter" || e.key === " ") {{ e.preventDefault(); go(); }}
    }});
  }});

  a.addEventListener("timeupdate", function () {{
    var t = a.currentTime, i = -1;
    for (var k = 0; k < segs.length; k++) {{
      if (t >= parseFloat(segs[k].dataset.start)) i = k; else break;
    }}
    if (i === cur) return;
    if (segs[cur]) segs[cur].classList.remove("on");
    cur = i;
    if (segs[cur]) {{
      segs[cur].classList.add("on");
      if (follow.getAttribute("aria-pressed") === "true") {{
        var r = segs[cur].getBoundingClientRect();
        if (r.top < 90 || r.bottom > innerHeight - 60) {{
          segs[cur].scrollIntoView({{ block: "center", behavior: "smooth" }});
        }}
      }}
    }}
  }});

  follow.onclick = function () {{
    follow.setAttribute("aria-pressed",
      follow.getAttribute("aria-pressed") === "true" ? "false" : "true");
  }};

  document.addEventListener("keydown", function (e) {{
    if (/^(INPUT|TEXTAREA)$/.test(e.target.tagName)) return;
    if (e.key === "ArrowLeft")  {{ a.currentTime = Math.max(0, a.currentTime - 5); }}
    if (e.key === "ArrowRight") {{ a.currentTime = a.currentTime + 5; }}
    if (e.key === " ") {{ e.preventDefault(); a.paused ? a.play() : a.pause(); }}
  }});
}})();
</script>
</div></body></html>
""", encoding="utf-8")

aligned = sum(1 for _, parts in rendered for s, _ in parts if s is not None)
print(f"{out}  ({out.stat().st_size / 1e6:.2f} MB, {len(rendered)} bloques, "
      f"{aligned}/{len(segments)} oraciones alineadas)")
