import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import {chromium} from 'playwright-core';
const base = path.join(os.homedir(), 'Library/Caches/ms-playwright');
const dd = fs.readdirSync(base).filter(x=>x.startsWith('chromium-')).sort((a,b)=>+a.split('-')[1]-+b.split('-')[1]).pop();
const exe = path.join(base, dd, 'chrome-mac-arm64','Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing');
const browser = await chromium.launch({executablePath: exe, args:['--autoplay-policy=no-user-gesture-required']});
const page = await (await browser.newContext({viewport:{width:1280,height:860}})).newPage();
page.on('request', r=>{ if(r.url().includes('/answer')) console.log('  POST answer:', r.postData()?.slice(0,160)); });
page.on('response', async r=>{ if(r.url().includes('/next')){ try{ const j=await r.json(); console.log('  /next ->', JSON.stringify(j).slice(0,160)); }catch{} }});
await page.goto('http://localhost:57330/?lang=es',{waitUntil:'domcontentloaded'});
await page.waitForFunction('window.__tutoria && window.__tutoria.media.duration()>0',null,{timeout:30000});
await page.evaluate(()=>{const m=window.__tutoria.media;m.seek(m.duration()-1.2);m.play();});
await page.waitForSelector('.dock-body .q .q-opcion',{timeout:20000}); await page.waitForTimeout(1200);
console.log('-- contesto la 1a mcq de practica');
await page.locator('.dock-body .q').last().locator('.q-opcion').nth(0).click();
await page.waitForTimeout(2500);
console.log('-- cruzo cp1');
await page.evaluate(()=>{const m=window.__tutoria.media;m.seek(142);m.play();});
await page.waitForTimeout(9000);
console.log('-- contesto el duplicado');
await page.locator('.dock-body .q').last().locator('.q-opcion').nth(0).click();
await page.waitForTimeout(2500);
await browser.close();
