import {abrir} from './_lib.mjs';
import {snap, dragTo, ultimoHTML} from './drv.mjs';
const {browser, page} = await abrir();
await page.evaluate(() => { window.__tutoria.media.seek(window.__tutoria.media.duration()-1.2); window.__tutoria.media.play(); });
await page.waitForTimeout(4000);
await snap(page,'I1');
await page.getByRole('button', {name:'Se desplaza hacia afuera, paralela'}).click();
await page.waitForTimeout(3000);
await snap(page,'I2');
await dragTo(page,1,62,56.625);
await dragTo(page,0,502.6,396);
await page.locator('.q-manip button.primario').last().click();
await page.waitForTimeout(3500);
await snap(page,'I3');
await page.locator('.q-numeric .q-input').last().fill('150');
await page.locator('.q-numeric button[type=submit]').last().click();
await page.waitForTimeout(3500);
await snap(page,'I4');
console.log('HTML I4:', await ultimoHTML(page));
await browser.close();
